version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - DEEPSEEK_API_KEY=sk-fc663842cc6c42a4ad1ec1ceac0f8ce2
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    depends_on:
      - backend

  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=wordcrafter
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data: 